#!/usr/bin/env node
/**
 * ko.json에서 TranslationKey 리터럴 유니온을 코드젠한다.
 * 배경: DotPaths 재귀 템플릿 타입은 키 ~400개 부근에서 TS 유니온이 truncate돼
 * 무관한 파일까지 typecheck가 전역 실패한다. 평탄한 리터럴 유니온 코드젠으로 대체.
 * 실행: pnpm --filter @aidetalk/i18n gen:keys (ko.json 키 변경 시마다)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const ko = JSON.parse(readFileSync(join(root, "../src/locales/ko.json"), "utf8"));

function leaves(obj, prefix = "") {
  return Object.entries(obj).flatMap(([k, v]) => {
    const path = prefix ? `${prefix}.${k}` : k;
    return typeof v === "string" ? [path] : leaves(v, path);
  });
}

const keys = leaves(ko);
const body = `/**
 * 자동 생성 파일 — 직접 수정 금지.
 * ko.json 키 변경 후 \`pnpm --filter @aidetalk/i18n gen:keys\`로 재생성한다.
 * (generated by scripts/gen-keys.mjs)
 */
export type TranslationKey =
${keys.map((k) => `  | "${k}"`).join("\n")};

/** 런타임 검증용 전체 키 목록(테스트에서 ko.json과 동기화를 강제). */
export const translationKeys = [
${keys.map((k) => `  "${k}",`).join("\n")}
] as const;
`;
writeFileSync(join(root, "../src/keys.generated.ts"), body);
console.log(`generated ${keys.length} keys`);
