/**
 * 자동 생성 파일 — 직접 수정 금지.
 * ko.json 키 변경 후 `pnpm --filter @aidetalk/i18n gen:keys`로 재생성한다.
 * (generated by scripts/gen-keys.mjs)
 */
export type TranslationKey =
  | "common.appName"
  | "common.loading"
  | "common.welcome"
  | "widget.launcherAriaOpen"
  | "widget.launcherAriaClose"
  | "widget.headerTitle"
  | "widget.headerClose"
  | "widget.connectAgent"
  | "widget.composerPlaceholder"
  | "widget.composerSend"
  | "widget.quickRepliesLabel"
  | "widget.emailPromptTitle"
  | "widget.emailPromptPlaceholder"
  | "widget.emailPromptSubmit"
  | "widget.emailPromptSkip"
  | "widget.typingAi"
  | "widget.typingHuman"
  | "widget.statusConnecting"
  | "widget.statusReconnecting"
  | "widget.statusPolling"
  | "widget.statusOffline"
  | "widget.messagePending"
  | "widget.messageFailed"
  | "widget.messageRetry"
  | "widget.readReceipt"
  | "widget.dateToday"
  | "widget.dateYesterday"
  | "widget.offHoursDefault"
  | "widget.errorGeneric"
  | "widget.errorConnection"
  | "widget.errorRateLimited"
  | "widget.errorDismiss"
  | "widget.headerSubtitle"
  | "widget.aiLabel"
  | "dashboard.meta.description"
  | "dashboard.common.save"
  | "dashboard.common.cancel"
  | "dashboard.common.delete"
  | "dashboard.common.edit"
  | "dashboard.common.copy"
  | "dashboard.common.copied"
  | "dashboard.common.close"
  | "dashboard.common.confirm"
  | "dashboard.common.back"
  | "dashboard.common.loading"
  | "dashboard.common.retry"
  | "dashboard.common.search"
  | "dashboard.common.none"
  | "dashboard.common.create"
  | "dashboard.common.add"
  | "dashboard.common.remove"
  | "dashboard.common.actions"
  | "dashboard.common.loadMore"
  | "dashboard.common.saved"
  | "dashboard.common.errorGeneric"
  | "dashboard.common.emptyGeneric"
  | "dashboard.datePicker.placeholder"
  | "dashboard.datePicker.rangePlaceholder"
  | "dashboard.auth.loginTitle"
  | "dashboard.auth.loginSubtitle"
  | "dashboard.auth.signupTitle"
  | "dashboard.auth.signupSubtitle"
  | "dashboard.auth.email"
  | "dashboard.auth.password"
  | "dashboard.auth.name"
  | "dashboard.auth.loginSubmit"
  | "dashboard.auth.signupSubmit"
  | "dashboard.auth.toSignup"
  | "dashboard.auth.toLogin"
  | "dashboard.auth.logout"
  | "dashboard.auth.loginFailed"
  | "dashboard.auth.signupFailed"
  | "dashboard.onboarding.title"
  | "dashboard.onboarding.subtitle"
  | "dashboard.onboarding.wsName"
  | "dashboard.onboarding.wsNamePlaceholder"
  | "dashboard.onboarding.segmentLabel"
  | "dashboard.onboarding.segmentS1Title"
  | "dashboard.onboarding.segmentS1Desc"
  | "dashboard.onboarding.segmentS2Title"
  | "dashboard.onboarding.segmentS2Desc"
  | "dashboard.onboarding.createSubmit"
  | "dashboard.invite.acceptTitle"
  | "dashboard.invite.acceptDesc"
  | "dashboard.invite.acceptSubmit"
  | "dashboard.invite.accepted"
  | "dashboard.invite.missingToken"
  | "dashboard.invite.needAuth"
  | "dashboard.invite.toSignup"
  | "dashboard.invite.toLogin"
  | "dashboard.nav.inbox"
  | "dashboard.nav.tracking"
  | "dashboard.nav.agents"
  | "dashboard.nav.settings"
  | "dashboard.nav.widget"
  | "dashboard.nav.members"
  | "dashboard.nav.workspace"
  | "dashboard.nav.webhooks"
  | "dashboard.nav.logs"
  | "dashboard.nav.switchWorkspace"
  | "dashboard.nav.logout"
  | "dashboard.theme.toggle"
  | "dashboard.theme.system"
  | "dashboard.theme.light"
  | "dashboard.theme.dark"
  | "dashboard.inboxSidebar.title"
  | "dashboard.inboxSidebar.mine"
  | "dashboard.inboxSidebar.all"
  | "dashboard.inboxSidebar.unread"
  | "dashboard.inboxSidebar.favorites"
  | "dashboard.inboxSidebar.unassigned"
  | "dashboard.inboxSidebar.byAssignee"
  | "dashboard.inboxSidebar.tags"
  | "dashboard.inboxSidebar.collapse"
  | "dashboard.inboxSidebar.expand"
  | "dashboard.inbox.filterOpen"
  | "dashboard.inbox.filterPending"
  | "dashboard.inbox.filterClosed"
  | "dashboard.inbox.searchPlaceholder"
  | "dashboard.inbox.empty"
  | "dashboard.inbox.emptyHint"
  | "dashboard.inbox.anonymousVisitor"
  | "dashboard.inbox.modeAi"
  | "dashboard.inbox.modeHuman"
  | "dashboard.inbox.unread"
  | "dashboard.inbox.aiSuggestion"
  | "dashboard.inbox.suggestionLabel"
  | "dashboard.inbox.newHandoffTitle"
  | "dashboard.inbox.selectConversation"
  | "dashboard.conversation.assign"
  | "dashboard.conversation.assignPlaceholder"
  | "dashboard.conversation.unassign"
  | "dashboard.conversation.assignSection"
  | "dashboard.conversation.returnToAi"
  | "dashboard.conversation.close"
  | "dashboard.conversation.reopen"
  | "dashboard.conversation.hold"
  | "dashboard.conversation.favorite"
  | "dashboard.conversation.unfavorite"
  | "dashboard.conversation.composerPlaceholder"
  | "dashboard.conversation.send"
  | "dashboard.conversation.modeSwitchHint"
  | "dashboard.conversation.viewLog"
  | "dashboard.conversation.readReceipt"
  | "dashboard.conversation.visitorTyping"
  | "dashboard.conversation.linkClickedAt"
  | "dashboard.conversation.linkNotClicked"
  | "dashboard.conversation.infoTitle"
  | "dashboard.conversation.infoSection"
  | "dashboard.conversation.visitorEmail"
  | "dashboard.conversation.visitorName"
  | "dashboard.conversation.attributes"
  | "dashboard.conversation.startPage"
  | "dashboard.conversation.otherConversations"
  | "dashboard.conversation.linksSection"
  | "dashboard.conversation.linksEmpty"
  | "dashboard.conversation.conversionSummary"
  | "dashboard.conversation.saveProfile"
  | "dashboard.conversation.togglePanel"
  | "dashboard.conversation.tabInfo"
  | "dashboard.conversation.tabAssist"
  | "dashboard.conversation.modeBadgeAi"
  | "dashboard.conversation.modeBadgeHuman"
  | "dashboard.conversation.statusOpen"
  | "dashboard.conversation.statusPending"
  | "dashboard.conversation.statusClosed"
  | "dashboard.tags.add"
  | "dashboard.tags.create"
  | "dashboard.tags.createWithName"
  | "dashboard.tags.searchPlaceholder"
  | "dashboard.tags.empty"
  | "dashboard.tags.deleteConfirm"
  | "dashboard.tags.duplicate"
  | "dashboard.tags.nameLabel"
  | "dashboard.tags.colorLabel"
  | "dashboard.tags.colorGray"
  | "dashboard.tags.colorRed"
  | "dashboard.tags.colorOrange"
  | "dashboard.tags.colorAmber"
  | "dashboard.tags.colorGreen"
  | "dashboard.tags.colorTeal"
  | "dashboard.tags.colorBlue"
  | "dashboard.tags.colorIndigo"
  | "dashboard.tags.colorPurple"
  | "dashboard.tags.colorPink"
  | "dashboard.notes.title"
  | "dashboard.notes.placeholder"
  | "dashboard.notes.save"
  | "dashboard.notes.edit"
  | "dashboard.notes.delete"
  | "dashboard.notes.deleteConfirm"
  | "dashboard.notes.empty"
  | "dashboard.notes.internalOnly"
  | "dashboard.customer.title"
  | "dashboard.customer.name"
  | "dashboard.customer.email"
  | "dashboard.customer.phone"
  | "dashboard.customer.none"
  | "dashboard.customer.edit"
  | "dashboard.customer.save"
  | "dashboard.customer.cancel"
  | "dashboard.customer.saved"
  | "dashboard.customer.showMore"
  | "dashboard.customer.showLess"
  | "dashboard.customer.device"
  | "dashboard.customer.firstSeen"
  | "dashboard.customer.lastSeen"
  | "dashboard.customer.referrer"
  | "dashboard.customer.language"
  | "dashboard.customer.timezone"
  | "dashboard.customer.utm"
  | "dashboard.event.handoff_auto"
  | "dashboard.event.handoff_agent"
  | "dashboard.event.handoff_requested"
  | "dashboard.event.returned_to_ai"
  | "dashboard.event.assigned"
  | "dashboard.event.unassigned"
  | "dashboard.event.closed"
  | "dashboard.event.reopened"
  | "dashboard.event.pending"
  | "dashboard.event.reasonSuffix"
  | "dashboard.assist.panelTitle"
  | "dashboard.assist.acceptRate"
  | "dashboard.assist.sendAsIs"
  | "dashboard.assist.editAndSend"
  | "dashboard.assist.ignore"
  | "dashboard.assist.rationaleLabel"
  | "dashboard.assist.ignored"
  | "dashboard.assist.empty"
  | "dashboard.assist.insertLink"
  | "dashboard.assist.onlyForAgent"
  | "dashboard.agents.title"
  | "dashboard.agents.description"
  | "dashboard.agents.registerTitle"
  | "dashboard.agents.registerDescription"
  | "dashboard.agents.registerButton"
  | "dashboard.agents.name"
  | "dashboard.agents.endpointUrl"
  | "dashboard.agents.endpointHint"
  | "dashboard.agents.timeoutMs"
  | "dashboard.agents.timeoutHint"
  | "dashboard.agents.assistEnabled"
  | "dashboard.agents.assistBadge"
  | "dashboard.agents.timeoutMeta"
  | "dashboard.agents.advancedShow"
  | "dashboard.agents.advancedHide"
  | "dashboard.agents.reactivate"
  | "dashboard.agents.autoDisabledCard"
  | "dashboard.agents.emptyDescription"
  | "dashboard.agents.secretReveal"
  | "dashboard.agents.secretHide"
  | "dashboard.agents.register"
  | "dashboard.agents.secretModalTitle"
  | "dashboard.agents.secretLabel"
  | "dashboard.agents.secretWarning"
  | "dashboard.agents.secretExampleTitle"
  | "dashboard.agents.exampleNode"
  | "dashboard.agents.examplePython"
  | "dashboard.agents.statusActive"
  | "dashboard.agents.statusDisabled"
  | "dashboard.agents.statusAutoDisabled"
  | "dashboard.agents.autoDisabledHint"
  | "dashboard.agents.test"
  | "dashboard.agents.testing"
  | "dashboard.agents.testOk"
  | "dashboard.agents.testFail"
  | "dashboard.agents.rotateSecret"
  | "dashboard.agents.rotateConfirm"
  | "dashboard.agents.enable"
  | "dashboard.agents.disable"
  | "dashboard.agents.empty"
  | "dashboard.agents.viewLogs"
  | "dashboard.agents.endpointPlaceholder"
  | "dashboard.agents.autoDisabledBanner"
  | "dashboard.agents.autoDisabledBannerLink"
  | "dashboard.webhooks.title"
  | "dashboard.webhooks.subtitle"
  | "dashboard.webhooks.listTitle"
  | "dashboard.webhooks.listDesc"
  | "dashboard.webhooks.registerTitle"
  | "dashboard.webhooks.registerDesc"
  | "dashboard.webhooks.url"
  | "dashboard.webhooks.urlPlaceholder"
  | "dashboard.webhooks.events"
  | "dashboard.webhooks.eventAutoDisabled"
  | "dashboard.webhooks.eventHandoff"
  | "dashboard.webhooks.register"
  | "dashboard.webhooks.statusActive"
  | "dashboard.webhooks.statusDisabled"
  | "dashboard.webhooks.empty"
  | "dashboard.webhooks.emptyDesc"
  | "dashboard.webhooks.removeConfirm"
  | "dashboard.webhooks.secretModalTitle"
  | "dashboard.webhooks.secretLabel"
  | "dashboard.logs.title"
  | "dashboard.logs.description"
  | "dashboard.logs.backToAgents"
  | "dashboard.logs.time"
  | "dashboard.logs.mode"
  | "dashboard.logs.modeAssist"
  | "dashboard.logs.outcome"
  | "dashboard.logs.latency"
  | "dashboard.logs.preview"
  | "dashboard.logs.filterOutcome"
  | "dashboard.logs.all"
  | "dashboard.logs.requestSummary"
  | "dashboard.logs.responseSummary"
  | "dashboard.logs.detailTitle"
  | "dashboard.logs.empty"
  | "dashboard.logs.outcomeReply"
  | "dashboard.logs.outcomeHandoff"
  | "dashboard.logs.outcomeNoop"
  | "dashboard.logs.outcomeSuggest"
  | "dashboard.logs.outcomeTimeout"
  | "dashboard.logs.outcomeError"
  | "dashboard.widget.title"
  | "dashboard.widget.subtitle"
  | "dashboard.widget.appearance"
  | "dashboard.widget.appearanceDesc"
  | "dashboard.widget.primaryColor"
  | "dashboard.widget.greeting"
  | "dashboard.widget.tone"
  | "dashboard.widget.toneFormal"
  | "dashboard.widget.toneCasual"
  | "dashboard.widget.launcherPosition"
  | "dashboard.widget.positionRight"
  | "dashboard.widget.positionLeft"
  | "dashboard.widget.officeHours"
  | "dashboard.widget.officeHoursDesc"
  | "dashboard.widget.officeHoursEnabled"
  | "dashboard.widget.officeHoursToggleHint"
  | "dashboard.widget.timezone"
  | "dashboard.widget.timezoneHint"
  | "dashboard.widget.rules"
  | "dashboard.widget.open"
  | "dashboard.widget.close"
  | "dashboard.widget.offHoursMessage"
  | "dashboard.widget.preview"
  | "dashboard.widget.previewDesc"
  | "dashboard.widget.install"
  | "dashboard.widget.embedCode"
  | "dashboard.widget.embedCodeHint"
  | "dashboard.widget.days.1"
  | "dashboard.widget.days.2"
  | "dashboard.widget.days.3"
  | "dashboard.widget.days.4"
  | "dashboard.widget.days.5"
  | "dashboard.widget.days.6"
  | "dashboard.widget.days.7"
  | "dashboard.widget.addRule"
  | "dashboard.widget.removeRule"
  | "dashboard.members.title"
  | "dashboard.members.subtitle"
  | "dashboard.members.listTitle"
  | "dashboard.members.listDesc"
  | "dashboard.members.invite"
  | "dashboard.members.inviteDesc"
  | "dashboard.members.inviteEmail"
  | "dashboard.members.inviteRole"
  | "dashboard.members.roleOwner"
  | "dashboard.members.roleAgent"
  | "dashboard.members.statusInvited"
  | "dashboard.members.statusActive"
  | "dashboard.members.inviteCreated"
  | "dashboard.members.inviteUrlCopy"
  | "dashboard.members.changeRole"
  | "dashboard.members.remove"
  | "dashboard.members.removeConfirm"
  | "dashboard.members.empty"
  | "dashboard.members.emptyDesc"
  | "dashboard.members.ownerOnly"
  | "dashboard.workspace.title"
  | "dashboard.workspace.subtitle"
  | "dashboard.workspace.general"
  | "dashboard.workspace.generalDesc"
  | "dashboard.workspace.name"
  | "dashboard.workspace.attributionRule"
  | "dashboard.workspace.attributionHint"
  | "dashboard.workspace.lastClick"
  | "dashboard.workspace.firstClick"
  | "dashboard.workspace.dangerZone"
  | "dashboard.workspace.exportCsv"
  | "dashboard.workspace.exportHint"
  | "dashboard.workspace.exportComingSoon"
  | "dashboard.workspace.billingTab"
  | "dashboard.workspace.billingCloudOnly"
  | "dashboard.tracking.title"
  | "dashboard.tracking.description"
  | "dashboard.tracking.period"
  | "dashboard.tracking.thisMonth"
  | "dashboard.tracking.totalConversations"
  | "dashboard.tracking.linkedConversations"
  | "dashboard.tracking.clickedConversations"
  | "dashboard.tracking.attributedRevenue"
  | "dashboard.tracking.attributedRevenueTooltip"
  | "dashboard.tracking.bySource"
  | "dashboard.tracking.bySourceEmpty"
  | "dashboard.tracking.sourceClickOnly"
  | "dashboard.tracking.sourcePixel"
  | "dashboard.tracking.pixelBanner"
  | "dashboard.tracking.gettingStartedTitle"
  | "dashboard.tracking.gettingStartedDesc"
  | "dashboard.tracking.gettingStartedCta"
  | "dashboard.tracking.empty"
  | "dashboard.confirm.title"
  | "dashboard.confirm.confirm"
  | "dashboard.confirm.cancel"
  | "dashboard.visitor.deletePii"
  | "dashboard.visitor.deletePiiTitle"
  | "dashboard.visitor.deletePiiConfirm"
  | "dashboard.visitor.deletePiiConfirmLabel"
  | "dashboard.visitor.deletePiiDone"
  | "errors.auth/invalid"
  | "errors.auth/forbidden"
  | "errors.validation/failed"
  | "errors.not_found"
  | "errors.rate/limited"
  | "errors.plan/limit_exceeded"
  | "errors.agent/timeout"
  | "errors.agent/bad_response"
  | "errors.conversion/duplicate"
  | "errors.conflict"
  | "errors.internal"
  | "errors.network"
  | "errors.unknown"
  | "server.handoffDefaultMessage"
  | "server.autoHandoffNotice"
  | "server.handoffRequestedReason"
  | "server.handoffAutoReason"
  | "server.messageRedacted";

/** 런타임 검증용 전체 키 목록(테스트에서 ko.json과 동기화를 강제). */
export const translationKeys = [
  "common.appName",
  "common.loading",
  "common.welcome",
  "widget.launcherAriaOpen",
  "widget.launcherAriaClose",
  "widget.headerTitle",
  "widget.headerClose",
  "widget.connectAgent",
  "widget.composerPlaceholder",
  "widget.composerSend",
  "widget.quickRepliesLabel",
  "widget.emailPromptTitle",
  "widget.emailPromptPlaceholder",
  "widget.emailPromptSubmit",
  "widget.emailPromptSkip",
  "widget.typingAi",
  "widget.typingHuman",
  "widget.statusConnecting",
  "widget.statusReconnecting",
  "widget.statusPolling",
  "widget.statusOffline",
  "widget.messagePending",
  "widget.messageFailed",
  "widget.messageRetry",
  "widget.readReceipt",
  "widget.dateToday",
  "widget.dateYesterday",
  "widget.offHoursDefault",
  "widget.errorGeneric",
  "widget.errorConnection",
  "widget.errorRateLimited",
  "widget.errorDismiss",
  "widget.headerSubtitle",
  "widget.aiLabel",
  "dashboard.meta.description",
  "dashboard.common.save",
  "dashboard.common.cancel",
  "dashboard.common.delete",
  "dashboard.common.edit",
  "dashboard.common.copy",
  "dashboard.common.copied",
  "dashboard.common.close",
  "dashboard.common.confirm",
  "dashboard.common.back",
  "dashboard.common.loading",
  "dashboard.common.retry",
  "dashboard.common.search",
  "dashboard.common.none",
  "dashboard.common.create",
  "dashboard.common.add",
  "dashboard.common.remove",
  "dashboard.common.actions",
  "dashboard.common.loadMore",
  "dashboard.common.saved",
  "dashboard.common.errorGeneric",
  "dashboard.common.emptyGeneric",
  "dashboard.datePicker.placeholder",
  "dashboard.datePicker.rangePlaceholder",
  "dashboard.auth.loginTitle",
  "dashboard.auth.loginSubtitle",
  "dashboard.auth.signupTitle",
  "dashboard.auth.signupSubtitle",
  "dashboard.auth.email",
  "dashboard.auth.password",
  "dashboard.auth.name",
  "dashboard.auth.loginSubmit",
  "dashboard.auth.signupSubmit",
  "dashboard.auth.toSignup",
  "dashboard.auth.toLogin",
  "dashboard.auth.logout",
  "dashboard.auth.loginFailed",
  "dashboard.auth.signupFailed",
  "dashboard.onboarding.title",
  "dashboard.onboarding.subtitle",
  "dashboard.onboarding.wsName",
  "dashboard.onboarding.wsNamePlaceholder",
  "dashboard.onboarding.segmentLabel",
  "dashboard.onboarding.segmentS1Title",
  "dashboard.onboarding.segmentS1Desc",
  "dashboard.onboarding.segmentS2Title",
  "dashboard.onboarding.segmentS2Desc",
  "dashboard.onboarding.createSubmit",
  "dashboard.invite.acceptTitle",
  "dashboard.invite.acceptDesc",
  "dashboard.invite.acceptSubmit",
  "dashboard.invite.accepted",
  "dashboard.invite.missingToken",
  "dashboard.invite.needAuth",
  "dashboard.invite.toSignup",
  "dashboard.invite.toLogin",
  "dashboard.nav.inbox",
  "dashboard.nav.tracking",
  "dashboard.nav.agents",
  "dashboard.nav.settings",
  "dashboard.nav.widget",
  "dashboard.nav.members",
  "dashboard.nav.workspace",
  "dashboard.nav.webhooks",
  "dashboard.nav.logs",
  "dashboard.nav.switchWorkspace",
  "dashboard.nav.logout",
  "dashboard.theme.toggle",
  "dashboard.theme.system",
  "dashboard.theme.light",
  "dashboard.theme.dark",
  "dashboard.inboxSidebar.title",
  "dashboard.inboxSidebar.mine",
  "dashboard.inboxSidebar.all",
  "dashboard.inboxSidebar.unread",
  "dashboard.inboxSidebar.favorites",
  "dashboard.inboxSidebar.unassigned",
  "dashboard.inboxSidebar.byAssignee",
  "dashboard.inboxSidebar.tags",
  "dashboard.inboxSidebar.collapse",
  "dashboard.inboxSidebar.expand",
  "dashboard.inbox.filterOpen",
  "dashboard.inbox.filterPending",
  "dashboard.inbox.filterClosed",
  "dashboard.inbox.searchPlaceholder",
  "dashboard.inbox.empty",
  "dashboard.inbox.emptyHint",
  "dashboard.inbox.anonymousVisitor",
  "dashboard.inbox.modeAi",
  "dashboard.inbox.modeHuman",
  "dashboard.inbox.unread",
  "dashboard.inbox.aiSuggestion",
  "dashboard.inbox.suggestionLabel",
  "dashboard.inbox.newHandoffTitle",
  "dashboard.inbox.selectConversation",
  "dashboard.conversation.assign",
  "dashboard.conversation.assignPlaceholder",
  "dashboard.conversation.unassign",
  "dashboard.conversation.assignSection",
  "dashboard.conversation.returnToAi",
  "dashboard.conversation.close",
  "dashboard.conversation.reopen",
  "dashboard.conversation.hold",
  "dashboard.conversation.favorite",
  "dashboard.conversation.unfavorite",
  "dashboard.conversation.composerPlaceholder",
  "dashboard.conversation.send",
  "dashboard.conversation.modeSwitchHint",
  "dashboard.conversation.viewLog",
  "dashboard.conversation.readReceipt",
  "dashboard.conversation.visitorTyping",
  "dashboard.conversation.linkClickedAt",
  "dashboard.conversation.linkNotClicked",
  "dashboard.conversation.infoTitle",
  "dashboard.conversation.infoSection",
  "dashboard.conversation.visitorEmail",
  "dashboard.conversation.visitorName",
  "dashboard.conversation.attributes",
  "dashboard.conversation.startPage",
  "dashboard.conversation.otherConversations",
  "dashboard.conversation.linksSection",
  "dashboard.conversation.linksEmpty",
  "dashboard.conversation.conversionSummary",
  "dashboard.conversation.saveProfile",
  "dashboard.conversation.togglePanel",
  "dashboard.conversation.tabInfo",
  "dashboard.conversation.tabAssist",
  "dashboard.conversation.modeBadgeAi",
  "dashboard.conversation.modeBadgeHuman",
  "dashboard.conversation.statusOpen",
  "dashboard.conversation.statusPending",
  "dashboard.conversation.statusClosed",
  "dashboard.tags.add",
  "dashboard.tags.create",
  "dashboard.tags.createWithName",
  "dashboard.tags.searchPlaceholder",
  "dashboard.tags.empty",
  "dashboard.tags.deleteConfirm",
  "dashboard.tags.duplicate",
  "dashboard.tags.nameLabel",
  "dashboard.tags.colorLabel",
  "dashboard.tags.colorGray",
  "dashboard.tags.colorRed",
  "dashboard.tags.colorOrange",
  "dashboard.tags.colorAmber",
  "dashboard.tags.colorGreen",
  "dashboard.tags.colorTeal",
  "dashboard.tags.colorBlue",
  "dashboard.tags.colorIndigo",
  "dashboard.tags.colorPurple",
  "dashboard.tags.colorPink",
  "dashboard.notes.title",
  "dashboard.notes.placeholder",
  "dashboard.notes.save",
  "dashboard.notes.edit",
  "dashboard.notes.delete",
  "dashboard.notes.deleteConfirm",
  "dashboard.notes.empty",
  "dashboard.notes.internalOnly",
  "dashboard.customer.title",
  "dashboard.customer.name",
  "dashboard.customer.email",
  "dashboard.customer.phone",
  "dashboard.customer.none",
  "dashboard.customer.edit",
  "dashboard.customer.save",
  "dashboard.customer.cancel",
  "dashboard.customer.saved",
  "dashboard.customer.showMore",
  "dashboard.customer.showLess",
  "dashboard.customer.device",
  "dashboard.customer.firstSeen",
  "dashboard.customer.lastSeen",
  "dashboard.customer.referrer",
  "dashboard.customer.language",
  "dashboard.customer.timezone",
  "dashboard.customer.utm",
  "dashboard.event.handoff_auto",
  "dashboard.event.handoff_agent",
  "dashboard.event.handoff_requested",
  "dashboard.event.returned_to_ai",
  "dashboard.event.assigned",
  "dashboard.event.unassigned",
  "dashboard.event.closed",
  "dashboard.event.reopened",
  "dashboard.event.pending",
  "dashboard.event.reasonSuffix",
  "dashboard.assist.panelTitle",
  "dashboard.assist.acceptRate",
  "dashboard.assist.sendAsIs",
  "dashboard.assist.editAndSend",
  "dashboard.assist.ignore",
  "dashboard.assist.rationaleLabel",
  "dashboard.assist.ignored",
  "dashboard.assist.empty",
  "dashboard.assist.insertLink",
  "dashboard.assist.onlyForAgent",
  "dashboard.agents.title",
  "dashboard.agents.description",
  "dashboard.agents.registerTitle",
  "dashboard.agents.registerDescription",
  "dashboard.agents.registerButton",
  "dashboard.agents.name",
  "dashboard.agents.endpointUrl",
  "dashboard.agents.endpointHint",
  "dashboard.agents.timeoutMs",
  "dashboard.agents.timeoutHint",
  "dashboard.agents.assistEnabled",
  "dashboard.agents.assistBadge",
  "dashboard.agents.timeoutMeta",
  "dashboard.agents.advancedShow",
  "dashboard.agents.advancedHide",
  "dashboard.agents.reactivate",
  "dashboard.agents.autoDisabledCard",
  "dashboard.agents.emptyDescription",
  "dashboard.agents.secretReveal",
  "dashboard.agents.secretHide",
  "dashboard.agents.register",
  "dashboard.agents.secretModalTitle",
  "dashboard.agents.secretLabel",
  "dashboard.agents.secretWarning",
  "dashboard.agents.secretExampleTitle",
  "dashboard.agents.exampleNode",
  "dashboard.agents.examplePython",
  "dashboard.agents.statusActive",
  "dashboard.agents.statusDisabled",
  "dashboard.agents.statusAutoDisabled",
  "dashboard.agents.autoDisabledHint",
  "dashboard.agents.test",
  "dashboard.agents.testing",
  "dashboard.agents.testOk",
  "dashboard.agents.testFail",
  "dashboard.agents.rotateSecret",
  "dashboard.agents.rotateConfirm",
  "dashboard.agents.enable",
  "dashboard.agents.disable",
  "dashboard.agents.empty",
  "dashboard.agents.viewLogs",
  "dashboard.agents.endpointPlaceholder",
  "dashboard.agents.autoDisabledBanner",
  "dashboard.agents.autoDisabledBannerLink",
  "dashboard.webhooks.title",
  "dashboard.webhooks.subtitle",
  "dashboard.webhooks.listTitle",
  "dashboard.webhooks.listDesc",
  "dashboard.webhooks.registerTitle",
  "dashboard.webhooks.registerDesc",
  "dashboard.webhooks.url",
  "dashboard.webhooks.urlPlaceholder",
  "dashboard.webhooks.events",
  "dashboard.webhooks.eventAutoDisabled",
  "dashboard.webhooks.eventHandoff",
  "dashboard.webhooks.register",
  "dashboard.webhooks.statusActive",
  "dashboard.webhooks.statusDisabled",
  "dashboard.webhooks.empty",
  "dashboard.webhooks.emptyDesc",
  "dashboard.webhooks.removeConfirm",
  "dashboard.webhooks.secretModalTitle",
  "dashboard.webhooks.secretLabel",
  "dashboard.logs.title",
  "dashboard.logs.description",
  "dashboard.logs.backToAgents",
  "dashboard.logs.time",
  "dashboard.logs.mode",
  "dashboard.logs.modeAssist",
  "dashboard.logs.outcome",
  "dashboard.logs.latency",
  "dashboard.logs.preview",
  "dashboard.logs.filterOutcome",
  "dashboard.logs.all",
  "dashboard.logs.requestSummary",
  "dashboard.logs.responseSummary",
  "dashboard.logs.detailTitle",
  "dashboard.logs.empty",
  "dashboard.logs.outcomeReply",
  "dashboard.logs.outcomeHandoff",
  "dashboard.logs.outcomeNoop",
  "dashboard.logs.outcomeSuggest",
  "dashboard.logs.outcomeTimeout",
  "dashboard.logs.outcomeError",
  "dashboard.widget.title",
  "dashboard.widget.subtitle",
  "dashboard.widget.appearance",
  "dashboard.widget.appearanceDesc",
  "dashboard.widget.primaryColor",
  "dashboard.widget.greeting",
  "dashboard.widget.tone",
  "dashboard.widget.toneFormal",
  "dashboard.widget.toneCasual",
  "dashboard.widget.launcherPosition",
  "dashboard.widget.positionRight",
  "dashboard.widget.positionLeft",
  "dashboard.widget.officeHours",
  "dashboard.widget.officeHoursDesc",
  "dashboard.widget.officeHoursEnabled",
  "dashboard.widget.officeHoursToggleHint",
  "dashboard.widget.timezone",
  "dashboard.widget.timezoneHint",
  "dashboard.widget.rules",
  "dashboard.widget.open",
  "dashboard.widget.close",
  "dashboard.widget.offHoursMessage",
  "dashboard.widget.preview",
  "dashboard.widget.previewDesc",
  "dashboard.widget.install",
  "dashboard.widget.embedCode",
  "dashboard.widget.embedCodeHint",
  "dashboard.widget.days.1",
  "dashboard.widget.days.2",
  "dashboard.widget.days.3",
  "dashboard.widget.days.4",
  "dashboard.widget.days.5",
  "dashboard.widget.days.6",
  "dashboard.widget.days.7",
  "dashboard.widget.addRule",
  "dashboard.widget.removeRule",
  "dashboard.members.title",
  "dashboard.members.subtitle",
  "dashboard.members.listTitle",
  "dashboard.members.listDesc",
  "dashboard.members.invite",
  "dashboard.members.inviteDesc",
  "dashboard.members.inviteEmail",
  "dashboard.members.inviteRole",
  "dashboard.members.roleOwner",
  "dashboard.members.roleAgent",
  "dashboard.members.statusInvited",
  "dashboard.members.statusActive",
  "dashboard.members.inviteCreated",
  "dashboard.members.inviteUrlCopy",
  "dashboard.members.changeRole",
  "dashboard.members.remove",
  "dashboard.members.removeConfirm",
  "dashboard.members.empty",
  "dashboard.members.emptyDesc",
  "dashboard.members.ownerOnly",
  "dashboard.workspace.title",
  "dashboard.workspace.subtitle",
  "dashboard.workspace.general",
  "dashboard.workspace.generalDesc",
  "dashboard.workspace.name",
  "dashboard.workspace.attributionRule",
  "dashboard.workspace.attributionHint",
  "dashboard.workspace.lastClick",
  "dashboard.workspace.firstClick",
  "dashboard.workspace.dangerZone",
  "dashboard.workspace.exportCsv",
  "dashboard.workspace.exportHint",
  "dashboard.workspace.exportComingSoon",
  "dashboard.workspace.billingTab",
  "dashboard.workspace.billingCloudOnly",
  "dashboard.tracking.title",
  "dashboard.tracking.description",
  "dashboard.tracking.period",
  "dashboard.tracking.thisMonth",
  "dashboard.tracking.totalConversations",
  "dashboard.tracking.linkedConversations",
  "dashboard.tracking.clickedConversations",
  "dashboard.tracking.attributedRevenue",
  "dashboard.tracking.attributedRevenueTooltip",
  "dashboard.tracking.bySource",
  "dashboard.tracking.bySourceEmpty",
  "dashboard.tracking.sourceClickOnly",
  "dashboard.tracking.sourcePixel",
  "dashboard.tracking.pixelBanner",
  "dashboard.tracking.gettingStartedTitle",
  "dashboard.tracking.gettingStartedDesc",
  "dashboard.tracking.gettingStartedCta",
  "dashboard.tracking.empty",
  "dashboard.confirm.title",
  "dashboard.confirm.confirm",
  "dashboard.confirm.cancel",
  "dashboard.visitor.deletePii",
  "dashboard.visitor.deletePiiTitle",
  "dashboard.visitor.deletePiiConfirm",
  "dashboard.visitor.deletePiiConfirmLabel",
  "dashboard.visitor.deletePiiDone",
  "errors.auth/invalid",
  "errors.auth/forbidden",
  "errors.validation/failed",
  "errors.not_found",
  "errors.rate/limited",
  "errors.plan/limit_exceeded",
  "errors.agent/timeout",
  "errors.agent/bad_response",
  "errors.conversion/duplicate",
  "errors.conflict",
  "errors.internal",
  "errors.network",
  "errors.unknown",
  "server.handoffDefaultMessage",
  "server.autoHandoffNotice",
  "server.handoffRequestedReason",
  "server.handoffAutoReason",
  "server.messageRedacted",
] as const;
